export const donorFields = [
  {
    labelText: "Donor Name",
    labelFor: "donorName",
    id: "donorName",
    name: "donorName",
    type: "text",
    autoComplete: "donorName",
    placeholder: "Donor Name",
    isRequired: true,
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    placeholder: "Email",
    isRequired: true,
  },
  {
    labelText: "Telephone",
    labelFor: "telephone",
    id: "telephone",
    name: "telephone",
    type: "text",
    autoComplete: "telephone",
    placeholder: "Telephone",
    isRequired: true,
  },
  {
    labelText: "Address",
    labelFor: "address",
    id: "address",
    name: "address",
    type: "text",
    autoComplete: "address",
    placeholder: "Address",
    isRequired: true,
  },
  {
    labelText: "Organization",
    labelFor: "organization",
    id: "organization",
    name: "organization",
    type: "text",
    autoComplete: "organization",
    placeholder: "Organization",
    isRequired: false,
  },
];

export const incomeFields = [
  {
    labelText: "Income Date",
    labelFor: "income_date",
    name: "income_date",
    type: "date",
    isRequired: true,
    placeholder: "Income Date",
    id: "income_date",
    autoComplete: "income_date",
  },
  {
    labelText: "Income Amount",
    labelFor: "amount",
    name: "amount",
    type: "number",
    isRequired: true,
    placeholder: "Income Amount",
    id: "amount",
    autoComplete: "amount",
  },
];
