export const educationFields = [
  {
    labelText: "School",
    labelFor: "school",
    id: "school",
    name: "school",
    type: "text",
    autoComplete: "school",
    isRequired: true,
    placeholder: "Enter school",
  },
  {
    labelText: "Degree",
    labelFor: "degree",
    id: "degree",
    name: "degree",
    type: "text",
    autoComplete: "degree",
    isRequired: true,
    placeholder: "Enter degree",
  },
  {
    labelText: "Field of Study",
    labelFor: "fieldofstudy",
    id: "fieldofstudy",
    name: "fieldofstudy",
    type: "text",
    autoComplete: "fieldofstudy",
    isRequired: true,
    placeholder: "Enter field of study",
  },
  {
    labelText: "From Date",
    labelFor: "startDate",
    id: "startDate",
    name: "startDate",
    type: "date",
    autoComplete: "startDate",
    isRequired: true,
    placeholder: "Enter from",
  },
  {
    labelText: "To Date(Or expected)",
    labelFor: "endDate",
    id: "endDate",
    name: "endDate",
    type: "date",
    autoComplete: "endDate",
    isRequired: true,
    placeholder: "Enter to",
  },
  {
    labelText: "Grade",
    labelFor: "grade",
    id: "grade",
    name: "grade",
    type: "text",
    autoComplete: "grade",
    isRequired: false,
    placeholder: "Enter grade",
  },
];

export const experienceFields = [
  {
    labelText: "Title",
    labelFor: "title",
    id: "title",
    name: "title",
    type: "text",
    autoComplete: "title",
    isRequired: true,
    placeholder: "Enter title",
  },
  {
    labelText: "Company",
    labelFor: "company",
    id: "company",
    name: "company",
    type: "text",
    autoComplete: "company",
    isRequired: true,
    placeholder: "Enter company",
  },
  {
    labelText: "Location",
    labelFor: "location",
    id: "location",
    name: "location",
    type: "text",
    autoComplete: "location",
    isRequired: true,
    placeholder: "Enter location",
  },
  {
    labelText: "From Date",
    labelFor: "startDate",
    id: "startDate",
    name: "startDate",
    type: "date",
    autoComplete: "startDate",
    isRequired: true,
    placeholder: "Enter from",
  },
  {
    labelText: "To Date",
    labelFor: "endDate",
    id: "endDate",
    name: "endDate",
    type: "date",
    autoComplete: "endDate",
    isRequired: false,
    placeholder: "Enter to",
  },

  {
    labelText: "Description",
    labelFor: "description",
    id: "description",
    name: "description",
    type: "text",
    autoComplete: "description",
    isRequired: false,
    placeholder: "Enter description",
  },
];

export const certificateFields = [
  {
    labelText: "Title",
    labelFor: "title",
    id: "title",
    name: "title",
    type: "text",
    autoComplete: "title",
    isRequired: true,
    placeholder: "Enter title",
  },
  {
    labelText: "Organization",
    labelFor: "organization",
    id: "organization",
    name: "organization",
    type: "text",
    autoComplete: "organization",
    isRequired: true,
    placeholder: "Enter organization",
  },
];
